version: '3'

services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.1
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
      - "--log.level=DEBUG"
      # - --entryPoints.http.address=:80
      # adds middleware at global level
      # - --entrypoints.http.http.middlewares=auth-server
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    # labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.default-router.rule=Host(`docker.localhost`) && PathPrefix(`/`)"
      # - "traefik.http.routers.default-router.priority=100"
      # - "traefik.http.middlewares.default-auth.forwardAuth.address=http://auth-server:8080/"
      # - "traefik.http.routers.default-router.middlewares=auth-middleware"
      # - "traefik.http.routers.default-router.entrypoints=websecure"
      # - "traefik.http.services.default-service.loadbalancer.server.port=8080"

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`docker.localhost`) && PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.priority=98"
      # adds middleware to this router
      - "traefik.http.routers.whoami.middlewares=auth-middleware"

  auth-server:
    # A container that exposes an API to show its IP address
    image: my-auth-server
    ports:
      - "8081:8080"
    labels:
      - "traefik.http.routers.auth-router.rule=Host(`docker.localhost`) && PathPrefix(`/login`)"
      - "traefik.http.routers.auth-router.priority=101"
    # registers itself as a forwardAuth middleware
      - "traefik.http.middlewares.auth-middleware.forwardAuth.address=http://auth-server:8080"
      # - "traefik.http.services.auth-server.loadbalancer.server.port=8080"